//require("./student")
//const studentName = require("./student")
const student = require("./student")
const {studentName, studentAge} = require("./student")
console.log("hello")
//console.log(studentName)
console.log(student.studentName)
console.log(student.studentAge)
console.log(studentName)
console.log(studentAge)